# Generated by Django 5.2.9 on 2026-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_alter_jobapplication_resume_job_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commitment',
            field=models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'OnSite')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'OnSite')], max_length=1000),
        ),
    ]
