# Generated by Django 5.2.9 on 2026-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_job_commitment_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('full-time', 'Full Time')], max_length=1000),
        ),
    ]
